# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:06:57+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ActionParameter(BaseModel):
    key: Optional[str] = Field(
        None, description='The name of the parameter for the action script.'
    )
    value: Optional[str] = Field(None, description='The value of the parameter.')


class Type(Enum):
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    NEW_MESSAGE = 'NEW_MESSAGE'
    UPDATE_MESSAGE = 'UPDATE_MESSAGE'
    UPDATE_USER_MESSAGE_CARDS = 'UPDATE_USER_MESSAGE_CARDS'
    REQUEST_CONFIG = 'REQUEST_CONFIG'
    DIALOG = 'DIALOG'


class StatusCode(Enum):
    OK = 'OK'
    CANCELLED = 'CANCELLED'
    UNKNOWN = 'UNKNOWN'
    INVALID_ARGUMENT = 'INVALID_ARGUMENT'
    DEADLINE_EXCEEDED = 'DEADLINE_EXCEEDED'
    NOT_FOUND = 'NOT_FOUND'
    ALREADY_EXISTS = 'ALREADY_EXISTS'
    PERMISSION_DENIED = 'PERMISSION_DENIED'
    UNAUTHENTICATED = 'UNAUTHENTICATED'
    RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED'
    FAILED_PRECONDITION = 'FAILED_PRECONDITION'
    ABORTED = 'ABORTED'
    OUT_OF_RANGE = 'OUT_OF_RANGE'
    UNIMPLEMENTED = 'UNIMPLEMENTED'
    INTERNAL = 'INTERNAL'
    UNAVAILABLE = 'UNAVAILABLE'
    DATA_LOSS = 'DATA_LOSS'


class ActionStatus(BaseModel):
    statusCode: Optional[StatusCode] = Field(None, description='The status code.')
    userFacingMessage: Optional[str] = Field(
        None,
        description='The message to send users about the status of their request. If unset, a generic message based on the `status_code` is sent.',
    )


class Type1(Enum):
    ANNOTATION_TYPE_UNSPECIFIED = 'ANNOTATION_TYPE_UNSPECIFIED'
    USER_MENTION = 'USER_MENTION'
    SLASH_COMMAND = 'SLASH_COMMAND'


class Source(Enum):
    SOURCE_UNSPECIFIED = 'SOURCE_UNSPECIFIED'
    DRIVE_FILE = 'DRIVE_FILE'
    UPLOADED_CONTENT = 'UPLOADED_CONTENT'


class AttachmentDataRef(BaseModel):
    resourceName: Optional[str] = Field(
        None,
        description='The resource name of the attachment data. This is used with the media API to download the attachment data.',
    )


class ImageStyle(Enum):
    IMAGE_STYLE_UNSPECIFIED = 'IMAGE_STYLE_UNSPECIFIED'
    IMAGE = 'IMAGE'
    AVATAR = 'AVATAR'


class CardHeader(BaseModel):
    imageStyle: Optional[ImageStyle] = Field(
        None, description="The image's type (e.g. square border or circular border)."
    )
    imageUrl: Optional[str] = Field(
        None, description='The URL of the image in the card header.'
    )
    subtitle: Optional[str] = Field(
        None, description='The subtitle of the card header.'
    )
    title: Optional[str] = Field(
        None,
        description='The title must be specified. The header has a fixed height: if both a title and subtitle is specified, each will take up 1 line. If only the title is specified, it will take up both lines.',
    )


class Color(BaseModel):
    alpha: Optional[float] = Field(
        None,
        description='The fraction of this color that should be applied to the pixel. That is, the final pixel color is defined by the equation: `pixel color = alpha * (this color) + (1.0 - alpha) * (background color)` This means that a value of 1.0 corresponds to a solid color, whereas a value of 0.0 corresponds to a completely transparent color. This uses a wrapper message rather than a simple float scalar so that it is possible to distinguish between a default value and the value being unset. If omitted, this color object is rendered as a solid color (as if the alpha value had been explicitly given a value of 1.0).',
    )
    blue: Optional[float] = Field(
        None,
        description='The amount of blue in the color as a value in the interval [0, 1].',
    )
    green: Optional[float] = Field(
        None,
        description='The amount of green in the color as a value in the interval [0, 1].',
    )
    red: Optional[float] = Field(
        None,
        description='The amount of red in the color as a value in the interval [0, 1].',
    )


class HostApp(Enum):
    UNSPECIFIED_HOST_APP = 'UNSPECIFIED_HOST_APP'
    GMAIL = 'GMAIL'
    CALENDAR = 'CALENDAR'
    DRIVE = 'DRIVE'
    DEMO = 'DEMO'
    DOCS = 'DOCS'
    MEET = 'MEET'
    SHEETS = 'SHEETS'
    SLIDES = 'SLIDES'
    DRAWINGS = 'DRAWINGS'
    CHAT = 'CHAT'


class Platform(Enum):
    UNKNOWN_PLATFORM = 'UNKNOWN_PLATFORM'
    WEB = 'WEB'
    IOS = 'IOS'
    ANDROID = 'ANDROID'


class DateInput(BaseModel):
    msSinceEpoch: Optional[str] = Field(
        None, description='Time since epoch time, in milliseconds.'
    )


class DateTimeInput(BaseModel):
    hasDate: Optional[bool] = Field(
        None, description='Whether the `datetime` input includes a calendar date.'
    )
    hasTime: Optional[bool] = Field(
        None, description='Whether the `datetime` input includes a timestamp.'
    )
    msSinceEpoch: Optional[str] = Field(
        None, description='Time since epoch time, in milliseconds.'
    )


class DialogEventType(Enum):
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    REQUEST_DIALOG = 'REQUEST_DIALOG'
    SUBMIT_DIALOG = 'SUBMIT_DIALOG'
    CANCEL_DIALOG = 'CANCEL_DIALOG'


class Type2(Enum):
    UNSPECIFIED = 'UNSPECIFIED'
    MESSAGE = 'MESSAGE'
    ADDED_TO_SPACE = 'ADDED_TO_SPACE'
    REMOVED_FROM_SPACE = 'REMOVED_FROM_SPACE'
    CARD_CLICKED = 'CARD_CLICKED'


class DriveDataRef(BaseModel):
    driveFileId: Optional[str] = Field(
        None, description='The id for the drive file, for use with the Drive API.'
    )


class Empty(BaseModel):
    pass


class FormAction(BaseModel):
    actionMethodName: Optional[str] = Field(
        None,
        description='The method name is used to identify which part of the form triggered the form submission. This information is echoed back to the Chat app as part of the card click event. The same method name can be used for several elements that trigger a common behavior if desired.',
    )
    parameters: Optional[List[ActionParameter]] = Field(
        None, description='List of action parameters.'
    )


class Interaction(Enum):
    INTERACTION_UNSPECIFIED = 'INTERACTION_UNSPECIFIED'
    OPEN_DIALOG = 'OPEN_DIALOG'


class LoadIndicator(Enum):
    SPINNER = 'SPINNER'
    NONE = 'NONE'


class GoogleAppsCardV1ActionParameter(BaseModel):
    key: Optional[str] = Field(
        None, description='The name of the parameter for the action script.'
    )
    value: Optional[str] = Field(None, description='The value of the parameter.')


class Type3(Enum):
    BORDER_TYPE_UNSPECIFIED = 'BORDER_TYPE_UNSPECIFIED'
    NO_BORDER = 'NO_BORDER'
    STROKE = 'STROKE'


class GoogleAppsCardV1BorderStyle(BaseModel):
    cornerRadius: Optional[int] = Field(
        None, description='The corner radius for the border.'
    )
    strokeColor: Optional[Color] = Field(
        None, description='The colors to use when the type is `BORDER_TYPE_STROKE`.'
    )
    type: Optional[Type3] = Field(None, description='The border type.')


class DisplayStyle(Enum):
    DISPLAY_STYLE_UNSPECIFIED = 'DISPLAY_STYLE_UNSPECIFIED'
    PEEK = 'PEEK'
    REPLACE = 'REPLACE'


class ImageType(Enum):
    SQUARE = 'SQUARE'
    CIRCLE = 'CIRCLE'


class GoogleAppsCardV1CardHeader(BaseModel):
    imageAltText: Optional[str] = Field(
        None,
        description='The alternative text of this image which is used for accessibility.',
    )
    imageType: Optional[ImageType] = Field(
        None, description='The shape used to crop the image.'
    )
    imageUrl: Optional[str] = Field(
        None, description='The HTTPS URL of the image in the card header.'
    )
    subtitle: Optional[str] = Field(
        None,
        description='The subtitle of the card header. If specified, appears on its own line below the `title`.',
    )
    title: Optional[str] = Field(
        None,
        description='Required. The title of the card header. The header has a fixed height: if both a title and subtitle are specified, each takes up one line. If only the title is specified, it takes up both lines.',
    )


class Type4(Enum):
    DATE_AND_TIME = 'DATE_AND_TIME'
    DATE_ONLY = 'DATE_ONLY'
    TIME_ONLY = 'TIME_ONLY'


class GoogleAppsCardV1Divider(BaseModel):
    pass


class Layout(Enum):
    GRID_ITEM_LAYOUT_UNSPECIFIED = 'GRID_ITEM_LAYOUT_UNSPECIFIED'
    TEXT_BELOW = 'TEXT_BELOW'
    TEXT_ABOVE = 'TEXT_ABOVE'


class GoogleAppsCardV1Icon(BaseModel):
    altText: Optional[str] = Field(
        None,
        description='Optional. A description of the icon used for accessibility. If unspecified, the default value "Button" is provided. As a best practice, you should set a helpful description for what the icon displays, and if applicable, what it does. For example, `A user\'s account portrait`, or `Opens a new browser tab and navigates to the Google Chat developer documentation at https://developers.google.com/chat`. If the icon is set in a Button, the `altText` appears as helper text when the user hovers over the button. However, if the button also sets `text`, the icon\'s `altText` is ignored.',
    )
    iconUrl: Optional[str] = Field(
        None,
        description='Display a custom icon hosted at an HTTPS URL. For example: ``` "iconUrl": "https://developers.google.com/chat/images/quickstart-app-avatar.png" ``` Supported file types include `.png` and `.jpg`.',
    )
    imageType: Optional[ImageType] = Field(
        None,
        description='The crop style applied to the image. In some cases, applying a `CIRCLE` crop causes the image to be drawn larger than a built-in icon.',
    )
    knownIcon: Optional[str] = Field(
        None,
        description='Display one of the built-in icons provided by Google Workspace. For example, to display an airplane icon, specify `AIRPLANE`. For a bus, specify `BUS`. For a full list of supported icons, see [built-in icons](https://developers.google.com/chat/api/guides/message-formats/cards#builtinicons).',
    )


class Type5(Enum):
    IMAGE_CROP_TYPE_UNSPECIFIED = 'IMAGE_CROP_TYPE_UNSPECIFIED'
    SQUARE = 'SQUARE'
    CIRCLE = 'CIRCLE'
    RECTANGLE_CUSTOM = 'RECTANGLE_CUSTOM'
    RECTANGLE_4_3 = 'RECTANGLE_4_3'


class GoogleAppsCardV1ImageCropStyle(BaseModel):
    aspectRatio: Optional[float] = Field(
        None,
        description='The aspect ratio to use if the crop type is `RECTANGLE_CUSTOM`. For example, here\'s how to apply a 16 by 9 aspect ratio: ``` cropStyle { "type": "RECTANGLE_CUSTOM", "aspectRatio": 16/9 } ```',
    )
    type: Optional[Type5] = Field(None, description='The crop type.')


class OnClose(Enum):
    NOTHING = 'NOTHING'
    RELOAD = 'RELOAD'


class OpenAs(Enum):
    FULL_SIZE = 'FULL_SIZE'
    OVERLAY = 'OVERLAY'


class GoogleAppsCardV1OpenLink(BaseModel):
    onClose: Optional[OnClose] = Field(
        None,
        description='Whether the client forgets about a link after opening it, or observes it until the window closes. Not supported by Chat apps.',
    )
    openAs: Optional[OpenAs] = Field(
        None, description='How to open a link. Not supported by Chat apps.'
    )
    url: Optional[str] = Field(None, description='The URL to open.')


class Type6(Enum):
    CHECK_BOX = 'CHECK_BOX'
    RADIO_BUTTON = 'RADIO_BUTTON'
    SWITCH = 'SWITCH'
    DROPDOWN = 'DROPDOWN'


class GoogleAppsCardV1SelectionItem(BaseModel):
    selected: Optional[bool] = Field(
        None,
        description='When `true`, more than one item is selected. If more than one item is selected for radio buttons and dropdown menus, the first selected item is received and the ones after are ignored.',
    )
    text: Optional[str] = Field(
        None, description='The text that identifies or describes the item to users.'
    )
    value: Optional[str] = Field(
        None,
        description='The value associated with this item. The client should use this as a form input value. For details about working with form inputs, see [Receive form data](https://developers.google.com/chat/how-tos/dialogs#receive_form_data_from_dialogs).',
    )


class GoogleAppsCardV1SuggestionItem(BaseModel):
    text: Optional[str] = Field(
        None,
        description='The value of a suggested input to a text input field. This is equivalent to what users would enter themselves.',
    )


class GoogleAppsCardV1Suggestions(BaseModel):
    items: Optional[List[GoogleAppsCardV1SuggestionItem]] = Field(
        None,
        description='A list of suggestions used for autocomplete recommendations in text input fields.',
    )


class ControlType(Enum):
    SWITCH = 'SWITCH'
    CHECKBOX = 'CHECKBOX'
    CHECK_BOX = 'CHECK_BOX'


class Type7(Enum):
    SINGLE_LINE = 'SINGLE_LINE'
    MULTIPLE_LINE = 'MULTIPLE_LINE'


class GoogleAppsCardV1TextParagraph(BaseModel):
    text: Optional[str] = Field(
        None, description="The text that's shown in the widget."
    )


class Icon(Enum):
    ICON_UNSPECIFIED = 'ICON_UNSPECIFIED'
    AIRPLANE = 'AIRPLANE'
    BOOKMARK = 'BOOKMARK'
    BUS = 'BUS'
    CAR = 'CAR'
    CLOCK = 'CLOCK'
    CONFIRMATION_NUMBER_ICON = 'CONFIRMATION_NUMBER_ICON'
    DOLLAR = 'DOLLAR'
    DESCRIPTION = 'DESCRIPTION'
    EMAIL = 'EMAIL'
    EVENT_PERFORMER = 'EVENT_PERFORMER'
    EVENT_SEAT = 'EVENT_SEAT'
    FLIGHT_ARRIVAL = 'FLIGHT_ARRIVAL'
    FLIGHT_DEPARTURE = 'FLIGHT_DEPARTURE'
    HOTEL = 'HOTEL'
    HOTEL_ROOM_TYPE = 'HOTEL_ROOM_TYPE'
    INVITE = 'INVITE'
    MAP_PIN = 'MAP_PIN'
    MEMBERSHIP = 'MEMBERSHIP'
    MULTIPLE_PEOPLE = 'MULTIPLE_PEOPLE'
    OFFER = 'OFFER'
    PERSON = 'PERSON'
    PHONE = 'PHONE'
    RESTAURANT_ICON = 'RESTAURANT_ICON'
    SHOPPING_CART = 'SHOPPING_CART'
    STAR = 'STAR'
    STORE = 'STORE'
    TICKET = 'TICKET'
    TRAIN = 'TRAIN'
    VIDEO_CAMERA = 'VIDEO_CAMERA'
    VIDEO_PLAY = 'VIDEO_PLAY'


class MatchedUrl(BaseModel):
    url: Optional[str] = Field(
        None, description='Output only. The url that was matched.'
    )


class Media(BaseModel):
    resourceName: Optional[str] = Field(None, description='Name of the media resource.')


class Role(Enum):
    MEMBERSHIP_ROLE_UNSPECIFIED = 'MEMBERSHIP_ROLE_UNSPECIFIED'
    ROLE_MEMBER = 'ROLE_MEMBER'
    ROLE_MANAGER = 'ROLE_MANAGER'


class State(Enum):
    MEMBERSHIP_STATE_UNSPECIFIED = 'MEMBERSHIP_STATE_UNSPECIFIED'
    JOINED = 'JOINED'
    INVITED = 'INVITED'
    NOT_A_MEMBER = 'NOT_A_MEMBER'


class OpenLink(BaseModel):
    url: Optional[str] = Field(None, description='The URL to open.')


class SlashCommand(BaseModel):
    commandId: Optional[str] = Field(
        None, description='The id of the slash command invoked.'
    )


class Type8(Enum):
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    ADD = 'ADD'
    INVOKE = 'INVOKE'


class SpaceThreadingState(Enum):
    SPACE_THREADING_STATE_UNSPECIFIED = 'SPACE_THREADING_STATE_UNSPECIFIED'
    THREADED_MESSAGES = 'THREADED_MESSAGES'
    GROUPED_MESSAGES = 'GROUPED_MESSAGES'
    UNTHREADED_MESSAGES = 'UNTHREADED_MESSAGES'


class Type9(Enum):
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    ROOM = 'ROOM'
    DM = 'DM'


class SpaceDetails(BaseModel):
    description: Optional[str] = Field(
        None,
        description="Optional. A description of the space. It could describe the space's discussion topic, functional purpose, or participants. Supports up to 150 characters.",
    )
    guidelines: Optional[str] = Field(
        None,
        description="Optional. The space's rules, expectations, and etiquette. Supports up to 5,000 characters.",
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class StringInputs(BaseModel):
    value: Optional[List[str]] = Field(
        None, description='An array of strings entered by the user.'
    )


class TextParagraph(BaseModel):
    text: Optional[str] = None


class Thread(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Resource name of the thread. Example: spaces/{space}/threads/{thread}',
    )
    threadKey: Optional[str] = Field(
        None,
        description='Optional. Opaque thread identifier. To start or add to a thread, create a message and specify a `threadKey` or the thread.name. For example usage, see [Start or reply to a message thread](https://developers.google.com/chat/api/guides/crudl/messages#start_or_reply_to_a_message_thread). For other requests, this is an output only field.',
    )


class TimeInput(BaseModel):
    hours: Optional[int] = Field(None, description='The hour on a 24-hour clock.')
    minutes: Optional[int] = Field(
        None,
        description='The number of minutes past the hour. Valid values are 0 to 59.',
    )


class TimeZone(BaseModel):
    id: Optional[str] = Field(
        None,
        description='The [IANA TZ](https://www.iana.org/time-zones) time zone database code, such as "America/Toronto".',
    )
    offset: Optional[int] = Field(
        None,
        description='The user timezone offset, in milliseconds, from Coordinated Universal Time (UTC).',
    )


class Type10(Enum):
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    HUMAN = 'HUMAN'
    BOT = 'BOT'


class User(BaseModel):
    displayName: Optional[str] = Field(
        None, description="Output only. The user's display name."
    )
    domainId: Optional[str] = Field(
        None, description="Unique identifier of the user's Google Workspace domain."
    )
    isAnonymous: Optional[bool] = Field(
        None,
        description='Output only. When `true`, the user is deleted or their profile is not visible.',
    )
    name: Optional[str] = Field(
        None,
        description='Resource name for a Google Chat user. Format: `users/{user}`. `users/app` can be used as an alias for the calling app bot user. For human users, `{user}` is the same user identifier as: - the `{person_id`} for the [Person](https://developers.google.com/people/api/rest/v1/people) in the People API, where the Person `resource_name` is `people/{person_id}`. For example, `users/123456789` in Chat API represents the same person as `people/123456789` in People API. - the `id` for a [user](https://developers.google.com/admin-sdk/directory/reference/rest/v1/users) in the Admin SDK Directory API.',
    )
    type: Optional[Type10] = Field(None, description='User type.')


class Type11(Enum):
    TYPE_UNSPECIFIED = 'TYPE_UNSPECIFIED'
    ADD = 'ADD'
    MENTION = 'MENTION'


class UserMentionMetadata(BaseModel):
    type: Optional[Type11] = Field(None, description='The type of user mention.')
    user: Optional[User] = Field(None, description='The user mentioned.')


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class MessageReplyOption(Enum):
    MESSAGE_REPLY_OPTION_UNSPECIFIED = 'MESSAGE_REPLY_OPTION_UNSPECIFIED'
    REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD = 'REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD'
    REPLY_MESSAGE_OR_FAIL = 'REPLY_MESSAGE_OR_FAIL'


class Attachment(BaseModel):
    attachmentDataRef: Optional[AttachmentDataRef] = Field(
        None,
        description='A reference to the attachment data. This is used with the media API to download the attachment data.',
    )
    contentName: Optional[str] = Field(
        None, description='The original file name for the content, not the full path.'
    )
    contentType: Optional[str] = Field(
        None, description='The content type (MIME type) of the file.'
    )
    downloadUri: Optional[str] = Field(
        None,
        description='Output only. The download URL which should be used to allow a human user to download the attachment. Chat apps should not use this URL to download attachment content.',
    )
    driveDataRef: Optional[DriveDataRef] = Field(
        None,
        description='A reference to the drive attachment. This is used with the Drive API.',
    )
    name: Optional[str] = Field(
        None,
        description='Resource name of the attachment, in the form "spaces/*/messages/*/attachments/*".',
    )
    source: Optional[Source] = Field(None, description='The source of the attachment.')
    thumbnailUri: Optional[str] = Field(
        None,
        description='Output only. The thumbnail URL which should be used to preview the attachment to a human user. Chat apps should not use this URL to download attachment content.',
    )


class ChatAppLogEntry(BaseModel):
    deployment: Optional[str] = Field(
        None,
        description='The deployment that caused the error. For Chat apps built in Apps Script, this is the deployment ID defined by Apps Script.',
    )
    deploymentFunction: Optional[str] = Field(
        None,
        description='The unencrypted `callback_method` name that was running when the error was encountered.',
    )
    error: Optional[Status] = Field(None, description='The error code and message.')


class GoogleAppsCardV1Action(BaseModel):
    function: Optional[str] = Field(
        None,
        description='A custom function to invoke when the containing element is clicked or othrwise activated. For example usage, see [Create interactive cards](https://developers.google.com/chat/how-tos/cards-onclick).',
    )
    interaction: Optional[Interaction] = Field(
        None,
        description='Optional. Required when opening a [dialog](https://developers.google.com/chat/how-tos/dialogs). What to do in response to an interaction with a user, such as a user clicking button on a card message. If unspecified, the app responds by executing an `action` - like opening a link or running a function - as normal. By specifying an `interaction`, the app can respond in special interactive ways. For example, by setting `interaction` to `OPEN_DIALOG`, the app can open a [dialog](https://developers.google.com/chat/how-tos/dialogs). When specified, a loading indicator is not shown. Supported by Chat apps, but not Google Workspace Add-ons. If specified for an add-on, the entire card is stripped and nothing is shown in the client.',
    )
    loadIndicator: Optional[LoadIndicator] = Field(
        None,
        description='Specifies the loading indicator that the action displays while making the call to the action.',
    )
    parameters: Optional[List[GoogleAppsCardV1ActionParameter]] = Field(
        None, description='List of action parameters.'
    )
    persistValues: Optional[bool] = Field(
        None,
        description="Indicates whether form values persist after the action. The default value is `false`. If `true`, form values remain after the action is triggered. To let the user make changes while the action is being processed, set [LoadIndicator](https://developers.google.com/workspace/add-ons/reference/rpc/google.apps.card.v1#loadindicator) to `NONE`. For [card messages](https://developers.google.com/chat/api/guides/message-formats/cards) in Chat apps, you must also set the action's [ResponseType](https://developers.google.com/chat/api/reference/rest/v1/spaces.messages#responsetype) to `UPDATE_MESSAGE` and use the same [`card_id`](https://developers.google.com/chat/api/reference/rest/v1/spaces.messages#CardWithId) from the card that contained the action. If `false`, the form values are cleared when the action is triggered. To prevent the user from making changes while the action is being processed, set [LoadIndicator](https://developers.google.com/workspace/add-ons/reference/rpc/google.apps.card.v1#loadindicator) to `SPINNER`.",
    )


class GoogleAppsCardV1DateTimePicker(BaseModel):
    label: Optional[str] = Field(
        None,
        description='The text that prompts users to enter a date, time, or datetime. Specify text that helps the user enter the information your app needs. For example, if users are setting an appointment, then a label like "Appointment date" or "Appointment date and time" might work well.',
    )
    name: Optional[str] = Field(
        None,
        description='The name by which the datetime picker is identified in a form input event. For details about working with form inputs, see [Receive form data](https://developers.google.com/chat/how-tos/dialogs#receive_form_data_from_dialogs).',
    )
    onChangeAction: Optional[GoogleAppsCardV1Action] = Field(
        None,
        description='Triggered when the user clicks **Save** or **Clear** from the datetime picker interface.',
    )
    timezoneOffsetDate: Optional[int] = Field(
        None,
        description="The number representing the time zone offset from UTC, in minutes. If set, the `value_ms_epoch` is displayed in the specified time zone. If not set, it uses the user's time zone setting on the client side.",
    )
    type: Optional[Type4] = Field(
        None,
        description='What kind of date and time input the datetime picker supports.',
    )
    valueMsEpoch: Optional[str] = Field(
        None,
        description='The value displayed as the default value before user input or previous user input, represented in milliseconds ([Epoch time](https://en.wikipedia.org/wiki/Unix_time)). For `DATE_AND_TIME` type, the full epoch value is used. For `DATE_ONLY` type, only date of the epoch time is used. For `TIME_ONLY` type, only time of the epoch time is used. For example, to represent 3:00 AM, set epoch time to `3 * 60 * 60 * 1000`.',
    )


class GoogleAppsCardV1ImageComponent(BaseModel):
    altText: Optional[str] = Field(
        None, description='The accessibility label for the image.'
    )
    borderStyle: Optional[GoogleAppsCardV1BorderStyle] = Field(
        None, description='The border style to apply to the image.'
    )
    cropStyle: Optional[GoogleAppsCardV1ImageCropStyle] = Field(
        None, description='The crop style to apply to the image.'
    )
    imageUri: Optional[str] = Field(None, description='The image URL.')


class GoogleAppsCardV1SelectionInput(BaseModel):
    items: Optional[List[GoogleAppsCardV1SelectionItem]] = Field(
        None,
        description='An array of selectable items. For example, an array of radio buttons or checkboxes. Supports up to 100 items.',
    )
    label: Optional[str] = Field(
        None,
        description='The text that appears above the selection input field in the user interface. Specify text that helps the user enter the information your app needs. For example, if users are selecting the urgency of a work ticket from a drop-down menu, the label might be "Urgency" or "Select urgency".',
    )
    name: Optional[str] = Field(
        None,
        description='The name that identifies the selection input in a form input event. For details about working with form inputs, see [Receive form data](https://developers.google.com/chat/how-tos/dialogs#receive_form_data_from_dialogs).',
    )
    onChangeAction: Optional[GoogleAppsCardV1Action] = Field(
        None,
        description='If specified, the form is submitted when the selection changes. If not specified, you must specify a separate button that submits the form. For details about working with form inputs, see [Receive form data](https://developers.google.com/chat/how-tos/dialogs#receive_form_data_from_dialogs).',
    )
    type: Optional[Type6] = Field(
        None,
        description='The type of items that are displayed to users in a `SelectionInput` widget. Selection types support different types of interactions. For example, users can select one or more checkboxes, but they can only select one value from a dropdown menu.',
    )


class GoogleAppsCardV1SwitchControl(BaseModel):
    controlType: Optional[ControlType] = Field(
        None, description='How the switch appears in the user interface.'
    )
    name: Optional[str] = Field(
        None,
        description='The name by which the switch widget is identified in a form input event. For details about working with form inputs, see [Receive form data](https://developers.google.com/chat/how-tos/dialogs#receive_form_data_from_dialogs).',
    )
    onChangeAction: Optional[GoogleAppsCardV1Action] = Field(
        None,
        description='The action to perform when the switch state is changed, such as what function to run.',
    )
    selected: Optional[bool] = Field(
        None, description='When `true`, the switch is selected.'
    )
    value: Optional[str] = Field(
        None,
        description='The value entered by a user, returned as part of a form input event. For details about working with form inputs, see [Receive form data](https://developers.google.com/chat/how-tos/dialogs#receive_form_data_from_dialogs).',
    )


class GoogleAppsCardV1TextInput(BaseModel):
    autoCompleteAction: Optional[GoogleAppsCardV1Action] = Field(
        None,
        description='Optional. Specify what action to take when the text input field provides suggestions to users who interact with it. If unspecified, the suggestions are set by `initialSuggestions` and are processed by the client. If specified, the app takes the action specified here, such as running a custom function. Supported by Google Workspace Add-ons, but not Chat apps.',
    )
    hintText: Optional[str] = Field(
        None,
        description='Text that appears below the text input field meant to assist users by prompting them to enter a certain value. This text is always visible. Required if `label` is unspecified. Otherwise, optional.',
    )
    initialSuggestions: Optional[GoogleAppsCardV1Suggestions] = Field(
        None,
        description='Suggested values that users can enter. These values appear when users click inside the text input field. As users type, the suggested values dynamically filter to match what the users have typed. For example, a text input field for programming language might suggest Java, JavaScript, Python, and C++. When users start typing "Jav", the list of suggestions filters to show just Java and JavaScript. Suggested values help guide users to enter values that your app can make sense of. When referring to JavaScript, some users might enter "javascript" and others "java script". Suggesting "JavaScript" can standardize how users interact with your app. When specified, `TextInput.type` is always `SINGLE_LINE`, even if it is set to `MULTIPLE_LINE`.',
    )
    label: Optional[str] = Field(
        None,
        description='The text that appears above the text input field in the user interface. Specify text that helps the user enter the information your app needs. For example, if you are asking someone\'s name, but specifically need their surname, write "surname" instead of "name". Required if `hintText` is unspecified. Otherwise, optional.',
    )
    name: Optional[str] = Field(
        None,
        description='The name by which the text input is identified in a form input event. For details about working with form inputs, see [Receive form data](https://developers.google.com/chat/how-tos/dialogs#receive_form_data_from_dialogs).',
    )
    onChangeAction: Optional[GoogleAppsCardV1Action] = Field(
        None,
        description='What to do when a change occurs in the text input field. Examples of changes include a user adding to the field, or deleting text. Examples of actions to take include running a custom function or opening a [dialog](https://developers.google.com/chat/how-tos/dialogs) in Google Chat.',
    )
    type: Optional[Type7] = Field(
        None,
        description='How a text input field appears in the user interface. For example, whether the field is single or multi-line.',
    )
    value: Optional[str] = Field(
        None,
        description='The value entered by a user, returned as part of a form input event. For details about working with form inputs, see [Receive form data](https://developers.google.com/chat/how-tos/dialogs#receive_form_data_from_dialogs).',
    )


class Inputs(BaseModel):
    dateInput: Optional[DateInput] = Field(None, description='Date input values.')
    dateTimeInput: Optional[DateTimeInput] = Field(
        None, description='Date and time input values.'
    )
    stringInputs: Optional[StringInputs] = Field(
        None,
        description='Input parameter for regular widgets. For single-valued widgets, it is a single value list. For multi-valued widgets, such as checkbox, all the values are presented.',
    )
    timeInput: Optional[TimeInput] = Field(None, description='Time input values.')


class Membership(BaseModel):
    createTime: Optional[str] = Field(
        None,
        description='Output only. The creation time of the membership, such as when a member joined or was invited to join a space.',
    )
    member: Optional[User] = Field(
        None, description='The Google Chat user or app the membership corresponds to.'
    )
    name: Optional[str] = Field(
        None,
        description='Resource name of the membership, assigned by the server. Format: spaces/{space}/members/{member}',
    )
    role: Optional[Role] = Field(
        None,
        description="Output only. User's role within a Chat space, which determines their permitted actions in the space.",
    )
    state: Optional[State] = Field(
        None, description='Output only. State of the membership.'
    )


class OnClick(BaseModel):
    action: Optional[FormAction] = Field(
        None,
        description='A form action will be triggered by this onclick if specified.',
    )
    openLink: Optional[OpenLink] = Field(
        None, description='This onclick triggers an open link action if specified.'
    )


class SlashCommandMetadata(BaseModel):
    bot: Optional[User] = Field(
        None, description='The Chat app whose command was invoked.'
    )
    commandId: Optional[str] = Field(
        None, description='The command id of the invoked slash command.'
    )
    commandName: Optional[str] = Field(
        None, description='The name of the invoked slash command.'
    )
    triggersDialog: Optional[bool] = Field(
        None, description='Indicating whether the slash command is for a dialog.'
    )
    type: Optional[Type8] = Field(None, description='The type of slash command.')


class Space(BaseModel):
    adminInstalled: Optional[bool] = Field(
        None,
        description='Output only. Whether the Chat app was installed by a Google Workspace administrator. Administrators can install a Chat app for their domain, organizational unit, or a group of users. Administrators can only install Chat apps for direct messaging between users and the app. To support admin install, your app must feature direct messaging.',
    )
    displayName: Optional[str] = Field(
        None,
        description="The space's display name. Required when [creating a space](https://developers.google.com/chat/api/reference/rest/v1/spaces/create). For direct messages, this field may be empty. Supports up to 128 characters.",
    )
    name: Optional[str] = Field(
        None, description='Resource name of the space. Format: spaces/{space}'
    )
    singleUserBotDm: Optional[bool] = Field(
        None,
        description='Optional. Whether the space is a DM between a Chat app and a single human.',
    )
    spaceDetails: Optional[SpaceDetails] = Field(
        None, description='Details about the space including description and rules.'
    )
    spaceThreadingState: Optional[SpaceThreadingState] = Field(
        None, description='Output only. The threading state in the Chat space.'
    )
    threaded: Optional[bool] = Field(
        None,
        description='Output only. Deprecated: Use `spaceThreadingState` instead. Whether messages are threaded in this space.',
    )
    type: Optional[Type9] = Field(
        None,
        description='Output only. Deprecated: Use `singleUserBotDm` or `spaceType` (developer preview) instead. The type of a space.',
    )


class TextButton(BaseModel):
    onClick: Optional[OnClick] = Field(
        None, description='The onclick action of the button.'
    )
    text: Optional[str] = Field(None, description='The text of the button.')


class Annotation(BaseModel):
    length: Optional[int] = Field(
        None,
        description='Length of the substring in the plain-text message body this annotation corresponds to.',
    )
    slashCommand: Optional[SlashCommandMetadata] = Field(
        None, description='The metadata for a slash command.'
    )
    startIndex: Optional[int] = Field(
        None,
        description='Start index (0-based, inclusive) in the plain-text message body this annotation corresponds to.',
    )
    type: Optional[Type1] = Field(None, description='The type of this annotation.')
    userMention: Optional[UserMentionMetadata] = Field(
        None, description='The metadata of user mention.'
    )


class CardAction(BaseModel):
    actionLabel: Optional[str] = Field(
        None, description='The label used to be displayed in the action menu item.'
    )
    onClick: Optional[OnClick] = Field(
        None, description='The onclick action for this action item.'
    )


class CommonEventObject(BaseModel):
    formInputs: Optional[Dict[str, Inputs]] = Field(
        None,
        description='A map containing the current values of the widgets in a card. The map keys are the string IDs assigned to each widget, and the values represent inputs to the widget. Depending on the input data type, a different object represents each input: For single-value widgets, `StringInput`. For multi-value widgets, an array of `StringInput` objects. For a date-time picker, a `DateTimeInput`. For a date-only picker, a `DateInput`. For a time-only picker, a `TimeInput`. Corresponds with the data entered by a user on a card in a [dialog](https://developers.google.com/chat/how-tos/dialogs).',
    )
    hostApp: Optional[HostApp] = Field(
        None,
        description='The hostApp enum which indicates the app the add-on is invoked from. Always `CHAT` for Chat apps.',
    )
    invokedFunction: Optional[str] = Field(
        None,
        description='Name of the invoked function associated with the widget. Only set for Chat apps.',
    )
    parameters: Optional[Dict[str, str]] = Field(
        None,
        description='Custom [parameters](/chat/api/reference/rest/v1/cards#ActionParameter) passed to the invoked function. Both keys and values must be strings.',
    )
    platform: Optional[Platform] = Field(
        None,
        description='The platform enum which indicates the platform where the event originates (`WEB`, `IOS`, or `ANDROID`). Not supported by Chat apps.',
    )
    timeZone: Optional[TimeZone] = Field(
        None,
        description='The timezone ID and offset from Coordinated Universal Time (UTC). Only supported for the event types [`CARD_CLICKED`](https://developers.google.com/chat/api/reference/rest/v1/EventType#ENUM_VALUES.CARD_CLICKED) and [`SUBMIT_DIALOG`](https://developers.google.com/chat/api/reference/rest/v1/DialogEventType#ENUM_VALUES.SUBMIT_DIALOG).',
    )
    userLocale: Optional[str] = Field(
        None,
        description='The full `locale.displayName` in the format of [ISO 639 language code]-[ISO 3166 country/region code] such as "en-US".',
    )


class GoogleAppsCardV1GridItem(BaseModel):
    id: Optional[str] = Field(
        None,
        description="A user-specified identifier for this grid item. This identifier is returned in the parent Grid's onClick callback parameters.",
    )
    image: Optional[GoogleAppsCardV1ImageComponent] = Field(
        None, description='The image that displays in the grid item.'
    )
    layout: Optional[Layout] = Field(
        None, description='The layout to use for the grid item.'
    )
    subtitle: Optional[str] = Field(None, description="The grid item's subtitle.")
    title: Optional[str] = Field(None, description="The grid item's title.")


class Image(BaseModel):
    aspectRatio: Optional[float] = Field(
        None,
        description="The aspect ratio of this image (width/height). This field allows clients to reserve the right height for the image while waiting for it to load. It's not meant to override the native aspect ratio of the image. If unset, the server fills it by prefetching the image.",
    )
    imageUrl: Optional[str] = Field(None, description='The URL of the image.')
    onClick: Optional[OnClick] = Field(None, description='The onclick action.')


class ImageButton(BaseModel):
    icon: Optional[Icon] = Field(
        None,
        description='The icon specified by an enum that indices to an icon provided by Chat API.',
    )
    iconUrl: Optional[str] = Field(None, description='The icon specified by a URL.')
    name: Optional[str] = Field(
        None,
        description="The name of this image_button which will be used for accessibility. Default value will be provided if developers don't specify.",
    )
    onClick: Optional[OnClick] = Field(None, description='The onclick action.')


class ListMembershipsResponse(BaseModel):
    memberships: Optional[List[Membership]] = Field(
        None, description='List of memberships in the requested (or first) page.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token that can be sent as `pageToken` to retrieve the next page of results. If empty, there are no subsequent pages.',
    )


class ListSpacesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token that can be sent as `pageToken` to retrieve the next page of results. If empty, there are no subsequent pages.',
    )
    spaces: Optional[List[Space]] = Field(
        None, description='List of spaces in the requested (or first) page.'
    )


class Button(BaseModel):
    imageButton: Optional[ImageButton] = Field(
        None, description='A button with image and onclick action.'
    )
    textButton: Optional[TextButton] = Field(
        None, description='A button with text and onclick action.'
    )


class KeyValue(BaseModel):
    bottomLabel: Optional[str] = Field(
        None,
        description='The text of the bottom label. Formatted text supported. For more information about formatting text, see Formatting text in Google Chat apps and Formatting text in Google Workspace Add-ons.',
    )
    button: Optional[Button] = Field(
        None, description='A button that can be clicked to trigger an action.'
    )
    content: Optional[str] = Field(
        None,
        description='The text of the content. Formatted text supported and always required. For more information about formatting text, see Formatting text in Google Chat apps and Formatting text in Google Workspace Add-ons.',
    )
    contentMultiline: Optional[bool] = Field(
        None, description='If the content should be multiline.'
    )
    icon: Optional[Icon] = Field(
        None,
        description='An enum value that will be replaced by the Chat API with the corresponding icon image.',
    )
    iconUrl: Optional[str] = Field(None, description='The icon specified by a URL.')
    onClick: Optional[OnClick] = Field(
        None,
        description='The onclick action. Only the top label, bottom label and content region are clickable.',
    )
    topLabel: Optional[str] = Field(
        None,
        description='The text of the top label. Formatted text supported. For more information about formatting text, see Formatting text in Google Chat apps and Formatting text in Google Workspace Add-ons.',
    )


class WidgetMarkup(BaseModel):
    buttons: Optional[List[Button]] = Field(
        None,
        description='A list of buttons. Buttons is also `oneof data` and only one of these fields should be set.',
    )
    image: Optional[Image] = Field(None, description='Display an image in this widget.')
    keyValue: Optional[KeyValue] = Field(
        None, description='Display a key value item in this widget.'
    )
    textParagraph: Optional[TextParagraph] = Field(
        None, description='Display a text paragraph in this widget.'
    )


class Section(BaseModel):
    header: Optional[str] = Field(
        None,
        description='The header of the section. Formatted text is supported. For more information about formatting text, see Formatting text in Google Chat apps and Formatting text in Google Workspace Add-ons.',
    )
    widgets: Optional[List[WidgetMarkup]] = Field(
        None, description='A section must contain at least 1 widget.'
    )


class Card(BaseModel):
    cardActions: Optional[List[CardAction]] = Field(
        None, description='The actions of this card.'
    )
    header: Optional[CardHeader] = Field(
        None,
        description='The header of the card. A header usually contains a title and an image.',
    )
    name: Optional[str] = Field(None, description='Name of the card.')
    sections: Optional[List[Section]] = Field(
        None, description='Sections are separated by a line divider.'
    )


class ActionResponse(BaseModel):
    dialogAction: Optional[DialogAction] = Field(
        None,
        description='Input only. A response to an event related to a [dialog](https://developers.google.com/chat/how-tos/dialogs). Must be accompanied by `ResponseType.Dialog`.',
    )
    type: Optional[Type] = Field(
        None, description='Input only. The type of Chat app response.'
    )
    url: Optional[str] = Field(
        None,
        description='Input only. URL for users to auth or config. (Only for REQUEST_CONFIG response types.)',
    )


class CardWithId(BaseModel):
    card: Optional[GoogleAppsCardV1Card] = Field(
        None,
        description='Cards support a defined layout, interactive UI elements like buttons, and rich media like images. Use this card to present detailed information, gather information from users, and guide users to take a next step.',
    )
    cardId: Optional[str] = Field(
        None,
        description='Required for `cardsV2` messages. Chat app-specified identifier for this widget. Scoped within a message.',
    )


class DeprecatedEvent(BaseModel):
    action: Optional[FormAction] = Field(
        None,
        description='The form action data associated with an interactive card that was clicked. Only populated for CARD_CLICKED events. See the [Interactive Cards guide](/chat/how-tos/cards-onclick) for more information.',
    )
    common: Optional[CommonEventObject] = Field(
        None,
        description="Represents information about the user's client, such as locale, host app, and platform. For Chat apps, `CommonEventObject` includes information submitted by users interacting with [dialogs](https://developers.google.com/chat/how-tos/dialogs), like data entered on a card.",
    )
    configCompleteRedirectUrl: Optional[str] = Field(
        None,
        description='The URL the Chat app should redirect the user to after they have completed an authorization or configuration flow outside of Google Chat. For more information, see [Connect a Chat app with other services & tools](https://developers.google.com/chat/how-tos/connect-web-services-tools).',
    )
    dialogEventType: Optional[DialogEventType] = Field(
        None,
        description='The type of [dialog](https://developers.google.com/chat/how-tos/dialogs) event received.',
    )
    eventTime: Optional[str] = Field(
        None, description='The timestamp indicating when the event occurred.'
    )
    isDialogEvent: Optional[bool] = Field(
        None,
        description='True when the event is related to [dialogs](https://developers.google.com/chat/how-tos/dialogs).',
    )
    message: Optional[Message] = Field(
        None, description='The message that triggered the event, if applicable.'
    )
    space: Optional[Space] = Field(
        None, description='The space in which the event occurred.'
    )
    threadKey: Optional[str] = Field(
        None,
        description='The Chat app-defined key for the thread related to the event. See [`spaces.messages.thread.threadKey`](/chat/api/reference/rest/v1/spaces.messages#Thread.FIELDS.thread_key) for more information.',
    )
    token: Optional[str] = Field(
        None,
        description="A secret value that legacy Chat apps can use to verify if a request is from Google. Google randomly generates the token, and its value remains static. You can obtain, revoke, or regenerate the token from the [Chat API configuration page](https://console.cloud.google.com/apis/api/chat.googleapis.com/hangouts-chat) in the Google Cloud Console. Modern Chat apps don't use this field. It is absent from API responses and the [Chat API configuration page](https://console.cloud.google.com/apis/api/chat.googleapis.com/hangouts-chat).",
    )
    type: Optional[Type2] = Field(None, description='The type of the event.')
    user: Optional[User] = Field(None, description='The user that triggered the event.')


class Dialog(BaseModel):
    body: Optional[GoogleAppsCardV1Card] = Field(
        None,
        description='Input only. Body of the dialog, which is rendered in a modal. Google Chat apps do not support the following card entities: `DateTimePicker`, `OnChangeAction`.',
    )


class DialogAction(BaseModel):
    actionStatus: Optional[ActionStatus] = Field(
        None,
        description='Input only. Status for a request to either invoke or submit a [dialog](https://developers.google.com/chat/how-tos/dialogs). Displays a status and message to users, if necessary. For example, in case of an error or success.',
    )
    dialog: Optional[Dialog] = Field(
        None,
        description='Input only. [Dialog](https://developers.google.com/chat/how-tos/dialogs) for the request.',
    )


class GoogleAppsCardV1Button(BaseModel):
    altText: Optional[str] = Field(
        None,
        description='The alternative text used for accessibility. Set descriptive text that lets users know what the button does. For example, if a button opens a hyperlink, you might write: "Opens a new browser tab and navigates to the Google Chat developer documentation at https://developers.google.com/chat".',
    )
    color: Optional[Color] = Field(
        None,
        description='If set, the button is filled with a solid background color and the font color changes to maintain contrast with the background color. For example, setting a blue background will likely result in white text. If unset, the image background is white and the font color is blue. For red, green and blue, the value of each field is a `float` number that can be expressed in either of two ways: as a number between 0 and 255 divided by 255 (153/255) or as a value between 0 and 1 (0.6). 0 represents the absence of a color and 1 or 255/255 represent the full presence of that color on the RGB scale. Optionally set alpha, which sets a level of transparency using this equation: ``` pixel color = alpha * (this color) + (1.0 - alpha) * (background color) ``` For alpha, a value of 1 corresponds with a solid color, and a value of 0 corresponds with a completely transparent color. For example, the following color represents a half transparent red: ``` "color": { "red": 1, "green": 0, "blue": 0, "alpha": 0.5 } ```',
    )
    disabled: Optional[bool] = Field(
        None,
        description="If `true`, the button is displayed in an inactive state and doesn't respond to user actions.",
    )
    icon: Optional[GoogleAppsCardV1Icon] = Field(
        None,
        description='The icon image. If both `icon` and `text` are set, then the icon appears before the text.',
    )
    onClick: Optional[GoogleAppsCardV1OnClick] = Field(
        None,
        description='Required. The action to perform when the button is clicked, such as opening a hyperlink or running a custom function.',
    )
    text: Optional[str] = Field(
        None, description='The text displayed inside the button.'
    )


class GoogleAppsCardV1ButtonList(BaseModel):
    buttons: Optional[List[GoogleAppsCardV1Button]] = Field(
        None, description='An array of buttons.'
    )


class GoogleAppsCardV1Card(BaseModel):
    cardActions: Optional[List[GoogleAppsCardV1CardAction]] = Field(
        None,
        description='The card\'s actions. Actions are added to the card\'s toolbar menu. Because Chat app cards have no toolbar, `cardActions[]` is not supported by Chat apps. For example, the following JSON constructs a card action menu with Settings and Send Feedback options: ``` "card_actions": [ { "actionLabel": "Settings", "onClick": { "action": { "functionName": "goToView", "parameters": [ { "key": "viewType", "value": "SETTING" } ], "loadIndicator": "LoadIndicator.SPINNER" } } }, { "actionLabel": "Send Feedback", "onClick": { "openLink": { "url": "https://example.com/feedback" } } } ] ```',
    )
    displayStyle: Optional[DisplayStyle] = Field(
        None,
        description='In Google Workspace add-ons, sets the display properties of the `peekCardHeader`. Not supported by Chat apps.',
    )
    fixedFooter: Optional[GoogleAppsCardV1CardFixedFooter] = Field(
        None,
        description='The fixed footer shown at the bottom of this card. Setting `fixedFooter` without specifying a `primaryButton` or a `secondaryButton` causes an error. Supported by Google Workspace Add-ons and Chat apps. For Chat apps, you can use fixed footers in [dialogs](https://developers.google.com/chat/how-tos/dialogs), but not [card messages](https://developers.google.com/chat/api/guides/message-formats/cards).',
    )
    header: Optional[GoogleAppsCardV1CardHeader] = Field(
        None,
        description='The header of the card. A header usually contains a leading image and a title. Headers always appear at the top of a card.',
    )
    name: Optional[str] = Field(
        None,
        description="Name of the card. Used as a card identifier in card navigation. Because Chat apps don't support card navigation, they ignore this field.",
    )
    peekCardHeader: Optional[GoogleAppsCardV1CardHeader] = Field(
        None,
        description='When displaying contextual content, the peek card header acts as a placeholder so that the user can navigate forward between the homepage cards and the contextual cards. Not supported by Chat apps.',
    )
    sections: Optional[List[GoogleAppsCardV1Section]] = Field(
        None,
        description='Contains a collection of widgets. Each section has its own, optional header. Sections are visually separated by a line divider.',
    )


class GoogleAppsCardV1CardAction(BaseModel):
    actionLabel: Optional[str] = Field(
        None, description='The label that displays as the action menu item.'
    )
    onClick: Optional[GoogleAppsCardV1OnClick] = Field(
        None, description='The `onClick` action for this action item.'
    )


class GoogleAppsCardV1CardFixedFooter(BaseModel):
    primaryButton: Optional[GoogleAppsCardV1Button] = Field(
        None,
        description='The primary button of the fixed footer. The button must be a text button with text and color set.',
    )
    secondaryButton: Optional[GoogleAppsCardV1Button] = Field(
        None,
        description='The secondary button of the fixed footer. The button must be a text button with text and color set. `primaryButton` must be set if `secondaryButton` is set.',
    )


class GoogleAppsCardV1DecoratedText(BaseModel):
    bottomLabel: Optional[str] = Field(
        None, description='The text that appears below `text`. Always truncates.'
    )
    button: Optional[GoogleAppsCardV1Button] = Field(
        None, description='A button that can be clicked to trigger an action.'
    )
    endIcon: Optional[GoogleAppsCardV1Icon] = Field(
        None,
        description='An icon displayed after the text. Supports [built-in](https://developers.google.com/chat/api/guides/message-formats/cards#builtinicons) and [custom](https://developers.google.com/chat/api/guides/message-formats/cards#customicons) icons.',
    )
    icon: Optional[GoogleAppsCardV1Icon] = Field(
        None, description='Deprecated in favor of `startIcon`.'
    )
    onClick: Optional[GoogleAppsCardV1OnClick] = Field(
        None,
        description='When users click on `topLabel` or `bottomLabel`, this action triggers.',
    )
    startIcon: Optional[GoogleAppsCardV1Icon] = Field(
        None, description='The icon displayed in front of the text.'
    )
    switchControl: Optional[GoogleAppsCardV1SwitchControl] = Field(
        None,
        description='A switch widget can be clicked to change its state and trigger an action.',
    )
    text: Optional[str] = Field(
        None,
        description='Required. The primary text. Supports simple formatting. For more information about formatting text, see Formatting text in Google Chat apps and Formatting text in Google Workspace Add-ons.',
    )
    topLabel: Optional[str] = Field(
        None, description='The text that appears above `text`. Always truncates.'
    )
    wrapText: Optional[bool] = Field(
        None,
        description='The wrap text setting. If `true`, the text wraps and displays on multiple lines. Otherwise, the text is truncated. Only applies to `text`, not `topLabel` and `bottomLabel`.',
    )


class GoogleAppsCardV1Grid(BaseModel):
    borderStyle: Optional[GoogleAppsCardV1BorderStyle] = Field(
        None, description='The border style to apply to each grid item.'
    )
    columnCount: Optional[int] = Field(
        None,
        description="The number of columns to display in the grid. A default value is used if this field isn't specified, and that default value is different depending on where the grid is shown (dialog versus companion).",
    )
    items: Optional[List[GoogleAppsCardV1GridItem]] = Field(
        None, description='The items to display in the grid.'
    )
    onClick: Optional[GoogleAppsCardV1OnClick] = Field(
        None,
        description="This callback is reused by each individual grid item, but with the item's identifier and index in the items list added to the callback's parameters.",
    )
    title: Optional[str] = Field(
        None, description='The text that displays in the grid header.'
    )


class GoogleAppsCardV1Image(BaseModel):
    altText: Optional[str] = Field(
        None, description='The alternative text of this image, used for accessibility.'
    )
    imageUrl: Optional[str] = Field(
        None,
        description='The `https` URL that hosts the image. For example: ``` https://developers.google.com/chat/images/quickstart-app-avatar.png ```',
    )
    onClick: Optional[GoogleAppsCardV1OnClick] = Field(
        None,
        description='When a user clicks on the image, the click triggers this action.',
    )


class GoogleAppsCardV1OnClick(BaseModel):
    action: Optional[GoogleAppsCardV1Action] = Field(
        None, description='If specified, an action is triggered by this `onClick`.'
    )
    card: Optional[GoogleAppsCardV1Card] = Field(
        None,
        description='A new card is pushed to the card stack after clicking if specified. Supported by Google Workspace Add-ons, but not Chat apps.',
    )
    openDynamicLinkAction: Optional[GoogleAppsCardV1Action] = Field(
        None,
        description='An add-on triggers this action when the action needs to open a link. This differs from the `open_link` above in that this needs to talk to server to get the link. Thus some preparation work is required for web client to do before the open link action response comes back.',
    )
    openLink: Optional[GoogleAppsCardV1OpenLink] = Field(
        None, description='If specified, this `onClick` triggers an open link action.'
    )


class GoogleAppsCardV1Section(BaseModel):
    collapsible: Optional[bool] = Field(
        None,
        description='Indicates whether this section is collapsible. Collapsible sections hide some or all widgets, but users can expand the section to reveal the hidden widgets by clicking **Show more**. Users can hide the widgets again by clicking **Show less**. To determine which widgets are hidden, specify `uncollapsibleWidgetsCount`.',
    )
    header: Optional[str] = Field(
        None,
        description='Text that appears at the top of a section. Supports simple HTML formatted text. For more information about formatting text, see Formatting text in Google Chat apps and Formatting text in Google Workspace Add-ons.',
    )
    uncollapsibleWidgetsCount: Optional[int] = Field(
        None,
        description='The number of uncollapsible widgets which remain visible even when a section is collapsed. For example, when a section contains five widgets and the `uncollapsibleWidgetsCount` is set to `2`, the first two widgets are always shown and the last three are collapsed by default. The `uncollapsibleWidgetsCount` is taken into account only when `collapsible` is `true`.',
    )
    widgets: Optional[List[GoogleAppsCardV1Widget]] = Field(
        None,
        description='All the widgets in the section. Must contain at least 1 widget.',
    )


class GoogleAppsCardV1Widget(BaseModel):
    buttonList: Optional[GoogleAppsCardV1ButtonList] = Field(
        None,
        description='A list of buttons. For example, the following JSON creates two buttons. The first is a blue text button and the second is an image button that opens a link: ``` "buttonList": { "buttons": [ { "text": "Edit", "color": { "red": 0, "green": 0, "blue": 1, "alpha": 1 }, "disabled": true, }, { "icon": { "knownIcon": "INVITE", "altText": "check calendar" }, "onClick": { "openLink": { "url": "https://example.com/calendar" } } } ] } ```',
    )
    dateTimePicker: Optional[GoogleAppsCardV1DateTimePicker] = Field(
        None,
        description='Displays a selection/input widget for date, time, or date and time. Not supported by Chat apps. Support by Chat apps is coming soon. For example, the following JSON creates a datetime picker to schedule an appointment: ``` "dateTimePicker": { "name": "appointment_time", "label": "Book your appointment at:", "type": "DATE_AND_TIME", "valueMsEpoch": "796435200000" } ```',
    )
    decoratedText: Optional[GoogleAppsCardV1DecoratedText] = Field(
        None,
        description='Displays a decorated text item. For example, the following JSON creates a decorated text widget showing email address: ``` "decoratedText": { "icon": { "knownIcon": "EMAIL" }, "topLabel": "Email Address", "text": "sasha@example.com", "bottomLabel": "This is a new Email address!", "switchControl": { "name": "has_send_welcome_email_to_sasha", "selected": false, "controlType": "CHECKBOX" } } ```',
    )
    divider: Optional[GoogleAppsCardV1Divider] = Field(
        None,
        description='Displays a horizontal line divider between widgets. For example, the following JSON creates a divider: ``` "divider": { } ```',
    )
    grid: Optional[GoogleAppsCardV1Grid] = Field(
        None,
        description='Displays a grid with a collection of items. A grid supports any number of columns and items. The number of rows is determined by the upper bounds of the number items divided by the number of columns. A grid with 10 items and 2 columns has 5 rows. A grid with 11 items and 2 columns has 6 rows. For example, the following JSON creates a 2 column grid with a single item: ``` "grid": { "title": "A fine collection of items", "columnCount": 2, "borderStyle": { "type": "STROKE", "cornerRadius": 4 }, "items": [ { "image": { "imageUri": "https://www.example.com/image.png", "cropStyle": { "type": "SQUARE" }, "borderStyle": { "type": "STROKE" } }, "title": "An item", "textAlignment": "CENTER" } ], "onClick": { "openLink": { "url": "https://www.example.com" } } } ```',
    )
    image: Optional[GoogleAppsCardV1Image] = Field(
        None,
        description='Displays an image. For example, the following JSON creates an image with alternative text: ``` "image": { "imageUrl": "https://developers.google.com/chat/images/quickstart-app-avatar.png", "altText": "Chat app avatar" } ```',
    )
    selectionInput: Optional[GoogleAppsCardV1SelectionInput] = Field(
        None,
        description='Displays a selection control that lets users select items. Selection controls can be checkboxes, radio buttons, switches, or dropdown menus. For example, the following JSON creates a dropdown menu that lets users choose a size: ``` "selectionInput": { "name": "size", "label": "Size" "type": "DROPDOWN", "items": [ { "text": "S", "value": "small", "selected": false }, { "text": "M", "value": "medium", "selected": true }, { "text": "L", "value": "large", "selected": false }, { "text": "XL", "value": "extra_large", "selected": false } ] } ```',
    )
    textInput: Optional[GoogleAppsCardV1TextInput] = Field(
        None,
        description='Displays a text box that users can type into. For example, the following JSON creates a text input for an email address: ``` "textInput": { "name": "mailing_address", "label": "Mailing Address" } ``` As another example, the following JSON creates a text input for a programming language with static suggestions: ``` "textInput": { "name": "preferred_programing_language", "label": "Preferred Language", "initialSuggestions": { "items": [ { "text": "C++" }, { "text": "Java" }, { "text": "JavaScript" }, { "text": "Python" } ] } } ```',
    )
    textParagraph: Optional[GoogleAppsCardV1TextParagraph] = Field(
        None,
        description='Displays a text paragraph. Supports simple HTML formatted text. For more information about formatting text, see Formatting text in Google Chat apps and Formatting text in Google Workspace Add-ons. For example, the following JSON creates a bolded text: ``` "textParagraph": { "text": " *bold text*" } ```',
    )


class Message(BaseModel):
    actionResponse: Optional[ActionResponse] = Field(
        None,
        description='Input only. Parameters that a Chat app can use to configure how its response is posted.',
    )
    annotations: Optional[List[Annotation]] = Field(
        None,
        description='Output only. Annotations associated with the text in this message.',
    )
    argumentText: Optional[str] = Field(
        None,
        description='Output only. Plain-text body of the message with all Chat app mentions stripped out.',
    )
    attachment: Optional[List[Attachment]] = Field(
        None, description='User-uploaded attachment.'
    )
    cards: Optional[List[Card]] = Field(
        None,
        description='Deprecated: Use `cards_v2` instead. Rich, formatted and interactive cards that can be used to display UI elements such as: formatted texts, buttons, clickable images. Cards are normally displayed below the plain-text body of the message. `cards` and `cards_v2` can have a maximum size of 32 KB.',
    )
    cardsV2: Optional[List[CardWithId]] = Field(
        None,
        description='Richly formatted and interactive cards that display UI elements and editable widgets, such as: - Formatted text - Buttons - Clickable images - Checkboxes - Radio buttons - Input widgets. Cards are usually displayed below the text body of a Chat message, but can situationally appear other places, such as [dialogs](https://developers.google.com/chat/how-tos/dialogs). Each card can have a maximum size of 32 KB. The `cardId` is a unique identifier among cards in the same message and for identifying user input values. Currently supported widgets include: - `TextParagraph` - `DecoratedText` - `Image` - `ButtonList` - `Divider` - `TextInput` - `SelectionInput` - `Grid`',
    )
    clientAssignedMessageId: Optional[str] = Field(
        None,
        description='A custom name for a Chat message assigned at creation. Must start with `client-` and contain only lowercase letters, numbers, and hyphens up to 63 characters in length. Specify this field to get, update, or delete the message with the specified value. For example usage, see [Name a created message](https://developers.google.com/chat/api/guides/crudl/messages#name_a_created_message).',
    )
    createTime: Optional[str] = Field(
        None,
        description='Output only. The time at which the message was created in Google Chat server.',
    )
    fallbackText: Optional[str] = Field(
        None,
        description="A plain-text description of the message's cards, used when the actual cards cannot be displayed (e.g. mobile notifications).",
    )
    lastUpdateTime: Optional[str] = Field(
        None,
        description='Output only. The time at which the message was last edited by a user. If the message has never been edited, this field is empty.',
    )
    matchedUrl: Optional[MatchedUrl] = Field(
        None,
        description='Output only. A URL in `spaces.messages.text` that matches a link preview pattern. For more information, refer to [Preview links](https://developers.google.com/chat/how-tos/preview-links).',
    )
    name: Optional[str] = Field(
        None,
        description='Resource name in the form `spaces/*/messages/*`. Example: `spaces/AAAAAAAAAAA/messages/BBBBBBBBBBB.BBBBBBBBBBB`',
    )
    sender: Optional[User] = Field(
        None,
        description='Output only. The user who created the message. If your Chat app [authenticates as a user](https://developers.google.com/chat/api/guides/auth/users), the output populates the [user](https://developers.google.com/chat/api/reference/rest/v1/User) `name` and `type`.',
    )
    slashCommand: Optional[SlashCommand] = Field(
        None, description='Output only. Slash command information, if applicable.'
    )
    space: Optional[Space] = Field(
        None,
        description='If your Chat app [authenticates as a user](https://developers.google.com/chat/api/guides/auth/users), the output populates the [space](https://developers.google.com/chat/api/reference/rest/v1/spaces) `name`.',
    )
    text: Optional[str] = Field(
        None,
        description='Plain-text body of the message. The first link to an image, video, web page, or other preview-able item generates a preview chip.',
    )
    thread: Optional[Thread] = Field(
        None,
        description='The thread the message belongs to. For example usage, see [Start or reply to a message thread](https://developers.google.com/chat/api/guides/crudl/messages#start_or_reply_to_a_message_thread).',
    )
    threadReply: Optional[bool] = Field(
        None,
        description="Output only. When `true`, the message is a response in a reply thread. When `false`, the message is visible in the space's top-level conversation as either the first message of a thread or a message with no threaded replies. If the space doesn't support reply in threads, this field is always `false`.",
    )


ActionResponse.model_rebuild()
CardWithId.model_rebuild()
DeprecatedEvent.model_rebuild()
Dialog.model_rebuild()
GoogleAppsCardV1Button.model_rebuild()
GoogleAppsCardV1Card.model_rebuild()
GoogleAppsCardV1CardAction.model_rebuild()
GoogleAppsCardV1DecoratedText.model_rebuild()
GoogleAppsCardV1Grid.model_rebuild()
GoogleAppsCardV1Image.model_rebuild()
GoogleAppsCardV1Section.model_rebuild()
